export const data = [
	{
		title: 'Egg sauce',
		img: '/img/b1.jpg',
		para: 'Egg sauce It’s typically one of Nigerian staple food that is perfect for breakfast.',
		price: '#1500',
		type: 'breakfast',
		id: 1,
	},
	{
		title: 'Abacha',
		img: '/img/lm5.jpg',
		para: 'African salad is native to the ndi Igbo (people of Igbo).',
		price: '#3000',
		type: 'lunch',
		id: 2,
	},
	{
		title: 'Boiled Potatoes',
		img: '/img/dm1.jpg',
		para: 'Boiled potatoes are highly nutritious mostly for kids and everyone contains fiber.',
		price: '#1000',
		type: 'dinner',
		id: 3,
	},
	{
		title: 'Grilled plantain',
		img: '/img/sm3.jpg',
		para: 'Grilled plantain are commonly called "bole in nigeria" eaten with roasted groundnut, smoked fish, palm-oil and pepper sauce. ',
		price: '#300',
		type: 'snacks',
		id: 4,
	},
	{
		title: 'Akara and Pap',
		img: '/img/b2.jpg',
		para: 'Akara and Pap is Naija’s weekend morning meal for most homes because of its light and filling nature.',
		price: '#300',
		type: 'breakfast',
		id: 5,
	},
	{
		title: 'Pounded yam and egusi soup',
		img: '/img/lm3.jpg',
		para: 'Pounded Yam and egusi is a very delicious meal.',
		price: '#2000',
		type: 'lunch',
		id: 6,
	},
	{
		title: 'Spagetti',
		img: '/img/dm3c.jpg',
		para: ' spaggetti is a starchy pasta of Italian origin that is made in the form of long strings, boiled, and served with any of a variety of meat, tomato, or other sauces.',
		price: '#1500',
		type: 'dinner',
		id: 7,
	},
	{
		title: 'Puff Puff',
		img: '/img/sm2.jpg',
		para: 'Puff-puff, as it is called in Nigeria and Sierra Leone, sometimes Ghana, and in anglophone Cameroon, is a traditional African snack made of fried dough.',
		price: '#200',
		type: 'snacks',
		id: 8,
	},
	{
		title: 'Toast Bread and Tea',
		img: '/img/b3.jpg',
		para: 'Most homes in nigeria love our bread toasted but served with sauce or drank with hot tea or chocolate drink',
		price: '#1000',
		type: 'breakfast',
		id: 9,
	},
	{
		title: 'Jollof rice',
		img: '/img/lm1.jpg',
		para: 'Jollof, or jollof rice, is a rice dish from West Africa. It is widely eaten by all.',
		price: '#2000',
		type: 'lunch',
		id: 10,
	},
	{
		title: 'Boiled plaintain',
		img: '/img/dm4a.jpg',
		para: 'Boiled plaintain are highly nutritious for everyone, boiled plaintain can be served with different sauce',
		price: '#2000',
		type: 'dinner',
		id: 11,
	},
	{
		title: 'corn',
		img: '/img/sm4.jpg',
		para: 'corn can highly nutritious and can be eaten roasted, boiled also can be eaten with coconut and pear',
		price: '#500',
		type: 'snacks',
		id: 12,
	},
];